# ============================================================
# Nexus Options - One-click GitHub Push Script
# ============================================================
# INSTRUCTIONS:
#   1. Create a new repo at https://github.com/new
#      - Name: kite-option-chain  (or anything you like)
#      - Visibility: Public
#      - DON'T initialize with README
#
#   2. Paste YOUR GitHub username below and the exact repo name
#      then run this script in PowerShell from d:\Antigravity:
#         .\push_to_github.ps1
#
# ============================================================

$GITHUB_USERNAME = "YOUR_GITHUB_USERNAME"   # ← change this
$REPO_NAME       = "kite-option-chain"       # ← change if you named it differently

# ─── Refresh PATH so git works ───────────────────────────────
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + `
            [System.Environment]::GetEnvironmentVariable("PATH","User")

# ─── Push to GitHub ──────────────────────────────────────────
$remote = "https://github.com/$GITHUB_USERNAME/$REPO_NAME.git"
git remote remove origin 2>$null
git remote add origin $remote
git branch -M main
git push -u origin main

Write-Host ""
Write-Host "✅  Code pushed to GitHub!" -ForegroundColor Green
Write-Host ""
Write-Host "═══════════════════════════════════════════════════════"
Write-Host "  Now deploy to Render in 3 steps:"
Write-Host ""
Write-Host "  1. Go to https://render.com → New → Web Service"
Write-Host "  2. Connect GitHub → select '$REPO_NAME'"
Write-Host "  3. Render auto-reads render.yaml — just add env vars:"
Write-Host ""
Write-Host "     KITE_API_KEY    = your api key"   -ForegroundColor Cyan
Write-Host "     KITE_API_SECRET = your api secret" -ForegroundColor Cyan
Write-Host "     (FLASK_SECRET_KEY is auto-generated by Render)"
Write-Host ""
Write-Host "  4. Click 'Create Web Service'  →  Done! 🎉"
Write-Host "═══════════════════════════════════════════════════════"
Write-Host ""
Write-Host "  Don't forget to set your Kite App Redirect URL to:"
Write-Host "  https://YOUR-RENDER-URL.onrender.com/callback" -ForegroundColor Yellow
Write-Host ""
